instana/python-sensor

instana/meter.py, instana/sensor.py, instana/tracer.py
This PR simply adds a `handle_fork` function to the tracer and sensor that can be used manually or eventually when we add pid change detection.
=> Add handle_fork function for eventual pid change detection

README.md
=> removed the BETA reference

instana/meter.py
supports #23
One of possible solutions to get information about modules that do not allow that.
=> ignores weird modules

instana/agent.py, instana/recorder.py
This fixes the issue where traces are not correctly linked to the reporting entity in the dashboard.
=> Fix entity reporting in spans.

instana/agent.py, instana/meter.py
Cosmetic change to logging levels.
=> Lower log levels for non-critical issues.

instana/agent.py
This change forces all object serialization to assure that all keys are lowercase.
=> Assure that all json keys are lowercase

instana/meter.py
This PR fixes an issue where thread counts show total threads instead of individualized values.
=> Fix thread count reporting.

Configuration.md, instana/__init__.py, instana/meter.py, instana/options.py, instana/recorder.py, instana/sensor.py
This PR improves the handling and config for service naming.  See the Configuration.md doc for usage.
=> Centralize & simplify service naming

instana/meter.py
* jsonable should always return a string
* more resilient snapshot creation
=> More resilient snapshot collection

instana/django.py
Django >=1.10 to <2.0 support old-style MIDDLEWARE_CLASSES so we do as well here
=> Support old-style MIDDLEWARE_CLASSES

instana/meter.py
=> Remove unused snapshot fields

Configuration.md
Add a note to the configuration document related to using the Python sensor in Openshift.
=> Add OpenShift note on exposing the host IP

.travis.yml, instana/__init__.py, instana/instrumentation/mysqlpython.py, instana/instrumentation/pep0249.py, instana/json_span.py, instana/recorder.py, instana/span.py, setup.py, tests/__init__.py, tests/apps/soapserver4132.py, tests/test_mysql-python.py, tests/test_sudsjurko.py, tests/test_urllib3.py
New instrumentation for the MySQL-python package:
https://pypi.org/project/MySQL-python/
=> MySQLdb Instrumentation (mysql-python)

instana/meter.py
Improvements to application naming in the dashboard.
This is mostly a review for various Python application types.
=> Better App Names

instana/instrumentation/django/middleware.py, instana/meter.py, instana/tracer.py, tests/test_api_client.py
Use `get_distribution` to alternatively extract version info
Don't include builtin modules
Improved exception logging
=> Snapshot reporting: Better version extraction

instana/instrumentation/django/middleware.py
This fixes potential context loss under high load.
=> Django: Store scope on the request object

instana/agent.py, instana/agent_const.py, instana/fsm.py, instana/http_propagator.py, instana/json_span.py, instana/meter.py, instana/recorder.py, instana/span.py, instana/text_propagator.py, instana/tracer.py, instana/util.py, instana/wsgi.py, setup.py, tests/test_django.py, tests/test_urllib3.py, tests/test_wsgi.py
- Use requests package: less memory, keep-alive and better API
- Greatly simplified Agent request functions into more logical components
- Much faster initial snapshot reporting (process details show up almost instantaneously now)
- Better error handling when complications with host agent arise
- This sensor can now handle agent tasks
- More import improvements and cleanup
=> Improved host agent communications

instana/api.py
See individual commit comments for details.
=> API improvements

instana/instrumentation/logging.py, tests/test_django.py, tests/test_logging.py, tests/test_sudsjurko.py, tests/test_urllib3.py
This PR adds some safeties to less common logging styles.  Update tests to include and test for the new log spans.
=> Logging instrumentation safeties; Update tests.

instana/json_span.py
Unify common span functionality into a base class
=> Improve JSON spans: Unify common elements

instana/__init__.py, instana/instrumentation/tornado/client.py, instana/instrumentation/tornado/server.py, instana/json_span.py, instana/recorder.py, instana/singletons.py, runtests.py, setup.py, tests/__init__.py, tests/apps/tornado.py, tests/test_tornado_client.py, tests/test_tornado_server.py
=> New Tornado instrumentation

instana/__init__.py, instana/instrumentation/tornado/client.py, instana/instrumentation/tornado/server.py, instana/meter.py, instana/recorder.py, instana/sensor.py, instana/singletons.py, tests/test_tornado_client.py, tests/test_tornado_server.py
=> Tornado: Polishing & Bug Fixes

.circleci/config.yml, instana/__init__.py, instana/__main__.py, instana/singletons.py, instana/tracer.py
* Don't load for all processes (such as pip, pipenv)
* More helpful debug boot msgs
=> More intelligent package loading semantics

instana/instrumentation/django/middleware.py
If we are instrumenting via AutoTrace (in an already running process), then the WSGI middleware has to be live reloaded.
=> Django: Support live reloading of middleware

instana/instrumentation/django/middleware.py
=> Django: If no app configured, pass

instana/__init__.py
Resolves issues that appear to be related to https://bugs.python.org/issue32573
=> Ensure we always have access to argv

instana/instrumentation/pika.py
closes: https://github.com/instana/python-sensor/issues/298
=> Fix: Pika Instrumentation errors/typos

tests/requirements-27.txt, tests/requirements.txt
Get ride of dependabot alerts by fixing Django versions
=> Update Django version requirements

instana/instrumentation/sanic_inst.py
This is the only change asked by Cedric, can go with any other future release
=> not setting the path_tpl at all when it evaluates to None

instana/instrumentation/cassandra_inst.py, instana/version.py, tests/clients/test_cassandra-driver.py, tests/requirements-cassandra.txt
Fixing the bug from here https://instana.zendesk.com/agent/tickets/23556
=> Testing cassandra

instana/collector/host.py
This PR fixes a misleading docstring, so people reading it won't get confused.
=> fix(doc): Fix host collector docstring

instana/version.py
The minor version is change because of support to suppression through X-INSTANA-L 0.
=> chore: Bump package version to 1.37.0

.circleci/config.yml, tests/clients/test_couchbase.py, tests/requirements-couchbase.txt
This PR reinstates the testing of the couchbase instrumentation.
=> fix(test/ci): Resurrect couchbase test

tests/clients/test_urllib3.py
There were some reports of tracing issues around ThreadPool, so let's add some coverage for that.
=> feat(test): Add TC for urllib with ThreadPool

.github/workflows/pr_commits_signed_off.yml, CONTRIBUTING.md
Adds instructions about contribution.
=> feat(doc): Add CONTRIBUTING.md

CONTRIBUTING.md, MAINTAINERS.md
Adds information about how to reach the maintainers
=> feat(doc): Add MAINTAINERS.md

tests/requirements-310-with-tornado.txt, tests/requirements-310.txt, tests/requirements.txt
=> fix(ci): Pin sanic version to the last working non vulnerable one

.circleci/config.yml
=> chore(ci): Update to the latest versions of runtimes

.circleci/config.yml, instana/collector/helpers/runtime.py, tests/clients/boto3/test_boto3_sqs.py, tests/requirements-307.txt
=> feat: Add option to disable package collection

tests/platforms/test_host_collector.py
=> Improve platform tests

.github/ISSUE_TEMPLATE/config.yml
=> docs: add link to AHA for feature requests to github issue template

.circleci/config.yml
=> ci: Store pytest results for CI display

.circleci/config.yml, tests/conftest.py, tests/opentracing/test_ot_span.py
=> ci+test: Start testing on Python 3.11

tests/platforms/test_host.py
* Modernizes and shortens host tests
=> Refactor host test

tests/requirements-307.txt, tests/requirements-310-with-tornado.txt, tests/requirements-310.txt, tests/requirements.txt
=> fix(ci): Pin SQLAlchemy version to pre-breaking change

instana/version.py
=> chore(version): Bump non-legacy version to 2.0.2

tests/clients/test_sqlalchemy.py
Adapts tests to SQLAlchemy 2.0
=> test: Adapt to SQLAlchemy 2.0

instana/version.py
Increments version for new patch release.
=> chore(version): Bump non-legacy version to 2.0.3

tests/clients/boto3/test_boto3_secretsmanager.py, tests/requirements-307.txt, tests/requirements-310-with-tornado.txt, tests/requirements-310.txt, tests/requirements-gevent.txt, tests/requirements.txt
Most of the upgrades are related to security issues of the packages or their dependencies (transitive).
=> Upgrade version of tests' dependencies.

tests/requirements-307.txt, tests/requirements-310-with-tornado.txt, tests/requirements-310.txt, tests/requirements.txt
Fixes recent CI failures on master branch.
=> Pin yarl and flask versions in CI jobs where it matters

tests/requirements-couchbase.txt
Update supported upper bound version for couchbase
=> ci: Update supported upper bound for couchbase

instana/version.py
=> chore(version): Bump version to 2.0.9

instana/version.py
=> Bump version to 2.0.10

instana/version.py
=> chore(version): Bump version to 2.1.0

bin/aws-lambda/build_and_publish_lambda_layer.py
Production code moved to `/src` directory in [this](https://github.com/instana/python-sensor/commit/b5b803c397cabd520e6a1d1c91a766202c5e7a6c) commit.
=> chore: fix lambda layer publish script

.tekton/.currency/resources/table.json
Update support policy in python currency report.
=> report(currency): update support policy

.tekton/.currency/currency-tasks.yaml, .tekton/.currency/resources/table.json
Update the Tracer support policy to 45 days instead of 30 days.
Fixed typos.
=> report(currency): Update support policy.

src/instana/instrumentation/logging.py, tests/clients/test_logging.py
- refactor logging instrumentation
- adapt logging unit tests to OTel spec
=> [OTel] Refactor logging instrumentation

pyproject.toml, src/instana/instrumentation/flask/__init__.py, src/instana/instrumentation/flask/common.py, src/instana/instrumentation/flask/vanilla.py, src/instana/instrumentation/flask/with_blinker.py, tests/apps/flask_app/app.py, tests/frameworks/test_flask.py
- with_blinker
- vanilla
- common
=> [Otel] flask instrumentation

src/instana/instrumentation/wsgi.py, src/instana/middleware.py, tests/apps/bottle_app/__init__.py, tests/apps/bottle_app/app.py, tests/apps/flask_app/app.py, tests/clients/boto3/test_boto3_sqs.py, tests/clients/test_urllib3.py, tests/conftest.py, tests/frameworks/test_aiohttp_client.py, tests/frameworks/test_asyncio.py, tests/frameworks/test_flask.py, tests/frameworks/test_gevent.py, tests/frameworks/test_wsgi.py, tests/requirements-310.txt, tests/requirements-312.txt, tests/requirements-313.txt, tests/requirements.txt
=> [OTel] Refactor WSGI instrumentation

.circleci/config.yml, src/instana/instrumentation/pep0249.py, tests/agent/test_host.py, tests/clients/test_pep0249.py, tests/conftest.py
- Added open telemetry support to pep0249 instrumentation.
- Added unittests.
- 99% coverage.
=> [OTel] pep0249 instrumentation

tests/apps/fastapi_app/app.py
Even with the code before suppression logic caused exception which wasn't logged. Now it fails as expected (due to no support for `httpx` used by `TestClient`)
```
tests/frameworks/test_fastapi.py::TestFastAPI::test_non_async_simple '<' not supported between instances of 'int' and 'NoneType'
```
=> Fix: test_non_async_simple

.tekton/task.yaml
added pubsub emulator for unittest-default
=> fix: added pubsub emulator

.tekton/.currency/docs/report.md, .tekton/.currency/scripts/generate_report.py
=> report(currency): Fetch google cloud task results

src/instana/__init__.py, src/instana/instrumentation/boto3_inst.py, tests/clients/boto3/README.md, tests/clients/boto3/test_boto3_lambda.py, tests/clients/boto3/test_boto3_s3.py, tests/clients/boto3/test_boto3_secretsmanager.py, tests/clients/boto3/test_boto3_ses.py, tests/clients/boto3/test_boto3_sqs.py, tests/conftest.py
=> [Otel] Refactor Boto3 instrumentation

src/instana/__init__.py, src/instana/instrumentation/mysqlclient.py, tests/clients/test_mysqlclient.py, tests/conftest.py
=> [OTel] Refactor of mysqlclient instrumentation

.circleci/config.yml, .tekton/.currency/currency-tasks.yaml, .tekton/pipeline.yaml, .tekton/python-tracer-prepuller.yaml, docker-compose.yml
Update CI images with the latest versions of Python runtimes.
=> Update Ci images

src/instana/version.py
=> chore(version): Bump version to 2.5.3

src/instana/__init__.py, src/instana/instrumentation/sqlalchemy.py, tests/clients/test_sqlalchemy.py, tests/conftest.py
=> [OTel] SQLAlchemy instrumentation

src/instana/__init__.py, src/instana/instrumentation/grpcio.py, tests/conftest.py, tests/frameworks/test_grpcio.py
`coverage: 95%`
- Type annotations will be handled later
=> [OTel] Grpcio instrumentation

.tekton/.currency/docs/report.md, .tekton/.currency/resources/table.json, .tekton/.currency/scripts/generate_report.py
- Update official reference site for WSGI
=> Fix: Currency report generation

src/instana/__init__.py, src/instana/hooks/hook_uwsgi.py
Added uWSGI hook support and tested using flask app on ubuntu.
=> [OTel] uwsgi: uWSGI Hook Support

.circleci/config.yml, .tekton/pipeline.yaml, .tekton/python-tracer-prepuller.yaml
Verify support for latest runtime versions.
=> ci: Verify support for latest runtime versions

src/instana/version.py
chore(version): Bump version to 3.2.0
=> chore(version): Bump version to 3.2.0

bin/aws-lambda/build_and_publish_lambda_layer.py
Add new AWS region `ap-southeast-7` to publish.
=> Fix: Add new AWS region `ap-southeast-7` to publish

src/instana/version.py
chore(version): Bump version to 3.3.0
=> chore(version): Bump version to 3.3.0

.tekton/.currency/resources/requirements.txt
added missing dependency for tekton
=> fix: updated tekton pipeline and currency generation

src/instana/agent/host.py, src/instana/util/span_utils.py, src/instana/util/traceutils.py, tests/agent/test_host.py, tests/clients/boto3/test_boto3_dynamodb.py, tests/util/test_span_utils.py, tests/util/test_traceutils.py
- Added Fair Usage Policy support for DynamoDB.
=> ft: add fup support for dynamodb

src/instana/version.py
=> chore(version): Bump version to 3.4.0

src/instana/instrumentation/aioamqp.py
Moved return statement into try block
=> fix: Function type has been updated

Dockerfile-py3140
=> fix (ci): Fix Python 3.14.0 container image build.

src/instana/version.py
=> chore(version): Bump version to 3.4.1

src/instana/version.py
=> chore(version): Bump version to 3.7.0

src/instana/version.py
=> chore(version): Bump version to 3.7.1

src/instana/version.py
chore(version): Bump version to 3.8.0
=> chore(version): Bump version to 3.8.0

src/instana/instrumentation/kafka/kafka_python.py
Added the missing suppression header reading part to the send message function.
=> fix: fixed reading suppression header from message's headers
