.travis.yml
instana/recorder.py
instana/util.py
tests/test_id_management.py

This PR fixes python 3 compatibility and adds python 3 to the Travis test runs.

Add python 3 compatibility

---

instana/agent.py
instana/django.py
instana/fsm.py
instana/log.py
instana/meter.py
instana/recorder.py

This PR fixes json encoding of snapshot data.  This is the cause
of the missing snapshot data on the dashboard.

Fix Snapshot JSON encoding

---

instana/agent.py
instana/meter.py

Fixes an error when encoding objects into json.

Fix json encoding error

---

README.md
instana/django.py
instana/django19.py
instana/options.py
instana/recorder.py
instana/runtime.py
instana/span.py
instana/wsgi.py

This PR fixes having spans marked as errored when a 5xx response is sent.

Improved error capture and reporting

---

instana/fsm.py

Basically, it fixes 2 pieces:
1. Hanging shell call in Docker container (as discovered, we need a `shell=True` there). Also the command itself was taken from golang sensor
2. One small bug when value must be updated before the condition

Fixes a bug with connecting to the agent

---

instana/fsm.py

This fixes a case seen on Travis where the value of `host` may be in bytes.

Make sure the arg we are passing is a string

---

example/Dockerfile
instana/agent.py
instana/fsm.py
instana/meter.py

This PR fixes the many pid == 1 issue when running inside of containers similar to what we do in other languages.
Remaining:

Implement advanced announce for containers

---

instana/meter.py

Because log object expects strings only

Convert exception to string

---

instana/recorder.py
instana/sensor.py

We are currently sending a custom service name always which we should avoid doing.
This PR updates the tracer to send a custom service name only when one is configured via `instana.Options`.

Fix: Custom Service Name Support

---

example/simple.py
instana/meter.py

This PR improves the naming of python processes.
Listed in order of precedence (highest to lowest) we use these names:
1. Tracer global service name: `instana.tracer.init(o.Options(service="ServiceName"))`
2. If a Flask or Django app, their respective configured names
3. The running python script via `sys.argv[0]`
Prior to this PR, entities would previously show up as:
With this fix, they now show up as:
and with a tracer configured global service name:

Better entity naming

---

instana/http_propagator.py
tests/test_ot_propagators.py

Depending on where `Inject` and `Extract` are being called from, the HTTP headers can vary in capitalization and prefix.
For example, in Flask and Django, in the middleware, HTTP headers are presented as all upper case, underscores and prefixed with `HTTP_` (Ruby also does this in Rack):
* `HTTP_X_INSTANA_T`
Yet in making requests via the `requests` package, HTTP headers are in the on-the-wire format:
* `X-Instana-T`
Our propagators should support all variations:
* Capitalization
* Underscores versus dashes
* Prefixed or not (only support `HTTP_` for now)

Propagators should support all forms of Instana Headers

---

.travis.yml
instana/__init__.py
instana/agent.py

This PR adds better handling for json strings that can show up as bytes (found in Python 3.5.2).
Also, update tests to be run against more Python versions.

Fix: Protect against byte based json

---

instana/meter.py

We currently report loaded submodules (`django.x, django.y, django.z`) which provide very little value in the snapshot.  This PR assures that we only report the top level module which is far less noise and makes the loaded modules pane much easier to read.

Snapshot: Don't report submodules

---

instana/agent.py
instana/fsm.py
instana/meter.py

- Track the last time the host agent was seen
- Properly timeout if more than 60 seconds
- Fallback into retry announce mode
- On timeout, let metric thread exit
- On successful announce, restart metric thread

Better offline handling

---

instana/fsm.py

This PR adds support for the `INSTANA_AGENT_IP` & `INSTANA_AGENT_PORT` environment variables to manually configure the location of the host agent.

Add host agent environment variable support.

---

Configuration.md
instana/__init__.py

There are cases when users of the python sensor may not want the automatic instrumentation to be used.  We should add a config option and environment variable to disable initialization of the automatic instrumentation.

Add config to disable automatic instrumentation

---

instana/instrumentation/urllib3.py
instana/tracer.py
tests/test_urllib3.py

This PR fixes the Urllib3 instrumentation to assure that it doesn't trace if there is no active trace happening.

Urllib3: Respect tracing state

---

instana/tracer.py

Limit tracer creation. Deprecate instana.tracer.init()

Deprecate instana.tracer.init()

---

README.md
instana/__init__.py
instana/eum.js
instana/eum_test.js
instana/helpers.py
tests/test_helpers.py

This PR adds a new helper method `instana.helpers.eum_snippet()` to insert an automagically configured EUM snippet into layouts and/or views.

EUM Helper & Tests

---

instana/instrumentation/urllib3.py
test_requirements.txt
tests/test_urllib3.py

* Fixes situation where requests package calls won't be traced
* Add tests that include calls via requests package

Hook lower in urllib3 for greater coverage

---

instana/instrumentation/urllib3.py

This fixes the case where if an exception is raised in `collect` that we don't incorrectly try to reference a key that might not be there.  This change also reduces the chance of an exception being raised in `collect`.

Urllib3: More safeties in KV collection & processing

---

Configuration.md
instana/fsm.py
instana/options.py

For the time being, we will still check for and use the INSTANA_HOST_IP environment variable but give INSTANA_AGENT_HOST priority going forward.
INSTANA_HOST_IP will be removed in a future version.

Standardize on INSTANA_AGENT_HOST; Deprecate *_IP

---

instana/meter.py

We use `threading.enumerate` to get a list of threads and currently report a count of dead threads but `enumerate` only returns the list of threads that are live.
This PR updates the thread metric reporting to not attempt to calculate dead threads and to also report a count of dummy threads.
Per the Python documentation:
```
threading.enumerate()
Return a list of all Thread objects currently alive. The list includes daemonic threads, dummy thread objects created by current_thread(), and the main thread. It excludes terminated threads and threads that have not yet been started.
```

Better thread metrics

---

instana/django.py

For Django >= 1.10, load middleware when load_middleware() is called.

Avoid pre-emptively loading Django middleware

---

instana/fsm.py

We have (had) a debug message that would log a debug message showing the currently running threads.
Doing this in certain versions of Python may cause an assertion error early in the boot process.

Remove debug message

---

instana/fsm.py
instana/log.py

When using custom logging is hard to override the handler and format of a logger that is named after a process id.
https://github.com/instana/python-sensor/blob/3810da69e05df351e54ca6685160acb9bd0a20f7/instana/log.py#L4
Use the LogRecord attributes to output a per process or per thread log in the format instead.
Optional, use the `dictConfig` to set up loggers.
https://github.com/instana/python-sensor/blob/3810da69e05df351e54ca6685160acb9bd0a20f7/instana/log.py#L9
`[%(process)d - %(thread)d] ...`
and name the logger `instana`
* https://docs.python.org/3/library/logging.html#logrecord-attributes
* https://docs.python.org/3/library/logging.config.html#logging.config.dictConfig

No pid in the logger instance

---

.travis.yml
instana/__init__.py
instana/instrumentation/mysqlpython.py
instana/instrumentation/pep0249.py
instana/span.py
setup.py
tests/__init__.py
tests/apps/soapserver4132.py
tests/test_mysql-python.py

New instrumentation for the MySQL-python package:
https://pypi.org/project/MySQL-python/

MySQLdb Instrumentation (mysql-python)

---

setup.py

Adds a check on install if setuptools==20.2.2 or greater is installed.  If that check fails, put out a clear message explaining how to resolve:

Add setuptools check on install with clear message

---

instana/__init__.py
instana/agent.py
instana/fsm.py
instana/meter.py
instana/recorder.py

Slightly delay full initialization before pulling triggers.

Better boot behaviour; Respect load dynamics

---

instana/__init__.py
instana/agent.py
instana/instrumentation/django/middleware.py
instana/recorder.py
instana/wsgi.py
tests/test_django.py
tests/test_wsgi.py

This adds support for collecting custom headers specified
in the Agent.

Support Custom Header collection

---

instana/json_span.py
instana/recorder.py

Report path templates in HTTP spans

Support Path Templates

---

instana/instrumentation/asynqp.py

This fix avoids the following stack trace which can occur under some versions of Python.
```
Exception in thread Thread-2:
File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/usr/lib/python3.6/threading.py", line 1182, in run
self.function(*self.args, **self.kwargs)
File "/tmp/instana/python/instana/__init__.py", line 62, in load_instrumentation
from .instrumentation import asynqp  # noqa
File "/tmp/instana/python/instana/instrumentation/asynqp.py", line 11, in <module>
import asyncio
File "/usr/lib/python3.6/asyncio/__init__.py", line 21, in <module>
from .base_events import *
File "/usr/lib/python3.6/asyncio/base_events.py", line 17, in <module>
import concurrent.futures
File …
```

Asynqp: Fix redundant import

---

instana/agent.py
instana/instrumentation/django/middleware.py
instana/instrumentation/urllib3.py
instana/json_span.py
instana/recorder.py
instana/singletons.py
instana/util.py
instana/wsgi.py
tests/test_secrets.py
tests/test_wsgi.py

Add support for secrets - to filter out sensitive data from collection as described here:
https://docs.instana.io/quick_start/agent_configuration/#secrets

Add support for HTTP secrets

---

instana/instrumentation/redis.py

The recent Redis 3.0 release has some breaking changes that we need to address/support.

Version limit redis until 3.0 is supported

---

instana/util.py
runtests.py

Improve secrets parsing to maintain key/value order across Python versions

Secrets: Improve to maintain query param order across Python versions

---

instana/__init__.py

Asynqp doesn't work on Py 3.7 - don't instrument it
https://github.com/benjamin-hodgson/asynqp/issues/108

Limit Asynqp instrumentation to Py versions >=3.4...<3.7

---

instana/meter.py
instana/options.py
instana/recorder.py

If the `INSTANA_SERVICE_NAME` environment variable is set, we should apply it's value consistently across tracing and snapshot reporting.

Respect INSTANA_SERVICE_NAME consistently.

---

instana/fsm.py
instana/util.py
setup.py

This also removes the external dependency of using /sbin/ip to determine host routes.

Use /proc/net/route to determine default gateway

---

instana/http_propagator.py
tests/test_django.py
tests/test_ot_propagators.py
tests/test_wsgi.py

This PR adds support for the `Server-Timing` header in HTTP responses for full EUM support.

Send Server-Timing in response headers

---

instana/__init__.py

This fixes load path priority for manually instrumented Python processes.

Only update working_set when loaded into live process

---

instana/__init__.py
instana/instrumentation/logging.py
instana/json_span.py
instana/recorder.py
tests/test_logging.py
tests/test_ot_span.py

Additional instrumentation for standard logging library.

New logging instrumentation

---

instana/agent.py
instana/json_span.py
instana/recorder.py
tests/test_ot_span.py
tests/test_ot_tracer.py

This PR replaces https://github.com/instana/python-sensor/pull/131

Improved JSON encoding, Kind handling & SDK span support

---

instana/instrumentation/asynqp.py

* Mark instrumented functions as coroutines

Asynqp Improvements

---

instana/meter.py

If the Python garbage collector is disabled, we were assuming the initialisation of a variable causing the following:
```
File "/Users/pglombardo/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/Users/pglombardo/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 865, in run
self._target(*self._args, **self._kwargs)
File "/Users/pglombardo/Projects/instana/python-sensor/instana/meter.py", line 149, in collect_and_report
self.process()
File "/Users/pglombardo/Projects/instana/python-sensor/instana/meter.py", line 161, in process
cm = self.collect_metrics()
File "/Users/pglombardo/Projects/instana/python-sensor/instana/meter.py", line 310, in collect_metrics
gc=g)
UnboundLocalError: local variable 'g' …
```

Fix case when GC is disabled; Add more safeties

---

Configuration.md
instana/__init__.py
instana/configurator.py
instana/instrumentation/asyncio.py
runtests.py
tests/test_asyncio.py
tests/test_configurator.py

Carry context across ensure_future calls

Asyncio: Carry context along with Tasks

---

instana/agent.py
instana/fsm.py
instana/meter.py
instana/recorder.py
instana/util.py

1. Better timing mechanism via `instana.util.every`:
a) avoids time drift
b) skip late executions (if runs become backed up under high load)
2. Add a new FSM state: "agent ready" to determine when host agent is ready to accept data (allows for #3)
3. Force snapshot reporting immediately once agent is ready to accept data (fixes inconsistent service naming as start-up)
This improves/fixes:
- Entity queue full when metric reporting may be backed up
- Sending initial spans without Infrastructure snapshot data.

Stability and determinism improvements

---

instana/instrumentation/asynqp.py
tests/test_asynqp.py

A case was identified where the incoming tuple of argv in publish_message
may be shorter than expected.  This change protects against accessing beyond
the length of the tuple.

Asynqp: Protect against short tuples

---

instana/http_propagator.py
instana/instrumentation/aiohttp/server.py
instana/instrumentation/django/middleware.py
instana/wsgi.py
tests/test_ot_propagators.py

OpenTracing propagators are ignorant of what type of carrier we are
inserting into (HTTP Server, HTTP Client, RabbitMQ message carrier)
and that gives us no way to conditionally insert optional headers
such as Server-Timing.
The possible alternative to to create a unique propagator for every case
but that is a lot of duplicated code and unecessary for this one current
exception.
This PR breaks Server-Timing handling out from the HTTP propagagor and 
inserts it manually when needed.

Handle Server-Timing headers manually

---

instana/instrumentation/tornado/client.py
instana/instrumentation/tornado/server.py
instana/singletons.py
runtests.py
tests/test_tornado_client.py

Avoid calling tornado if not installed

Tornado: Don't import modules if not installed

---

tests/helpers.py
tests/test_tornado_server.py

There was some non-determinisim in the tornado test suite
due to mixed event loop usage.
Use tornado loop directly and consistently

Improved Tornado Tests

---

.circleci/config.yml

Add test runs for the above Python versions as well.

CircleCI: Add test runs for Python 2.7 and Python 3.5

---

instana/agent.py
instana/fsm.py
instana/meter.py
instana/recorder.py

* Assure worker threads are shutdown post fork
* Don't reuse thread objects post fork (create new ones)

Improved thread management & safety

---

instana/__main__.py

This PR adds the ability to invoke an instana console with:
python -m instana console
The console depends on ipython and is not installed by default with Instana.
To enable the console, you must install ipython.  Package output describes as much.

Console support

---

instana/__init__.py
instana/instrumentation/pep0249.py
instana/instrumentation/pymysql.py
instana/util.py
setup.py
tests/helpers.py
tests/test_pymysql.py

New Instrumentation for the [PyMySQL](https://pypi.org/project/PyMySQL/#description) package.

PyMySQL Instrumentation, support and tests

---

instana/agent.py
instana/instrumentation/redis.py

Also: Make sure that we don't send empty trace payloads

Redis: Validate min version before instrumenting

---

instana/instrumentation/psycopg2.py

Also: Make sure not to send empty trace payloads

Psycopg2: Assure index exists before referencing

---

instana/meter.py

Check if uwsgi API available and use to detect environment

Improved uWSGI & GUnicorn App Names

---

docker-compose.yml
instana/agent.py
instana/instrumentation/redis.py
instana/recorder.py
instana/util.py
instana/wsgi.py
tests/helpers.py
tests/test_redis.py

1. More instrumentation safeties
2. Redis Sentinel support
3. Improved JSON encoding safeties

Redis Visibility Improvements

---

instana/util.py

Add explicit initialization of hip variable

---

instana/instrumentation/flask/__init__.py
instana/instrumentation/flask/common.py
instana/instrumentation/flask/vanilla.py
instana/instrumentation/flask/with_blinker.py
tests/apps/flaskalino.py
tests/test_flask.py
tests/test_sudsjurko.py
tests/test_urllib3.py

Noted by @steveww:
>Just calling logging.error('foo') works when in the body of the route.
> It does not work when inside an error handler.
```
import instana
import logging
import json
from flask import Flask
app = Flask(__name__)
@app.errorhandler(Exception)
def exception_handler(err):
app.logger.error(str(err))
return str(err), 500
@app.route('/health', methods=['GET'])
def health():
return 'OK'
@app.route('/warning', methods=['GET'])
def warning():
app.logger.warn('This is a warning')
return 'warning', 400
@app.route('/error', methods=['GET'])
def error():
app.logger.error('This is an error')
return 'error', 500
@app.route('/rerror', methods=['GET'])
def rerror():
found_it = False
my_list = None
for i in my_list:
if i == 'foo':
found_it = True
return found_it
if __name__ == …
```

Log spans may not be created when inside of a Flask Error Handler

---

instana/agent.py
instana/fsm.py
instana/log.py
instana/meter.py
instana/sensor.py
setup.py

Check for and conditionally use the gunicorn logger
* A few improved logging messages
* Greatly improved log module
* Determine if we are running in a gunicorn package.  if so, use the gunicorn logger
* Otherwise retrieve and configure a standard logger

Detect and conditionally use the Gunicorn logger

---

instana/log.py

Hello,
I am using instana Python library v1.15.4 with Odoo v12 (http://odoo.com) in a virtual environment.
When I start Odoo with:
```
export AUTOWRAPT_BOOTSTRAP=instana
```
I get the following error message:
```
/home/mchambreuil/odoo/12/env/bin/python /home/mchambreuil/odoo/12/env/bin/odoo -c odoo.conf 
Failed to import the site module
File "/usr/lib/python3.6/site.py", line 570, in <module>
main()
File "/usr/lib/python3.6/site.py", line 563, in main
execsitecustomize()
File "/home/mchambreuil/odoo/12/env/lib/python3.6/site-packages/autowrapt/bootstrap.py", line 32, in _execsitecustomize
return wrapped(*args, **kwargs)
File "/home/mchambreuil/odoo/12/env/lib/python3.6/site-packages/autowrapt/bootstrap.py", line 38, in _execsitecustomize …
```

Instana 1.15.4 with Odoo 12 - AttributeError: module 'sys' has no attribute 'argv'

---

instana/fsm.py

This PR lowers the time for the schedule timer for first agent lookup.  This results in a faster initial announce.

Faster Announce: Lower agent lookup time from boot

---

instana/meter.py

At boot, if the sys.modules dict changed while we were iterating it for snapshot data, it would put out a warning.
```
RuntimeError: dictionary changed size during iteration
```
This PR avoids getting that warning by making a copy of the dict and iterating the copy instead.

Avoid dict changed warning by copying

---

instana/__init__.py
instana/instrumentation/webapp2_inst.py

This PR adds support for the webapp2 framework:
https://webapp2.readthedocs.io/en/latest/index.html
https://pypi.org/project/webapp2/

webapp2: New automatic instrumentation

---

instana/instrumentation/flask/vanilla.py
instana/instrumentation/flask/with_blinker.py

This fixes the case of:
```
During handling of the above exception, another exception occurred:
File "/usr/local/lib/python3.6/site-packages/instana/instrumentation/flask/with_blinker.py", line 105, in handle_user_exception_with_instana
response.headers.add('Server-Timing', "intid;desc=%s" % scope.span.context.trace_id)
AttributeError: 'dict' object has no attribute 'add'
```

Flask: Add context injection safeties

---

.circleci/config.yml
instana/__init__.py
instana/instrumentation/couchbase_inst.py
instana/json_span.py
instana/recorder.py
setup.py
tests/helpers.py
tests/test_couchbase.py

This PR adds visibility for the [couchbase package](https://pypi.org/project/couchbase/)

New couchbase instrumentation

---

instana/instrumentation/aiohttp/server.py
tests/apps/app_aiohttp.py
tests/test_aiohttp.py

Reported via https://github.com/instana/python-sensor/issues/193, this PR:
* Properly re-raises any caught framework exceptions
* Logs a HTTP status code when a general exception is caught
* Now places the Instana middleware first in the list of middlewares

aiohttp server: Error handling and reporting improvements

---

instana/instrumentation/psycopg2.py

running this wrapper-
```
@wrapt.patch_function_wrapper('psycopg2.extensions', 'register_type')
def register_type_with_instana(wrapped, instance, args, kwargs):
args_clone = list(copy.copy(args))
if (len(args_clone) >= 2) and hasattr(args_clone[1], '__wrapped__'):
args_clone[1] = args_clone[1].__wrapped__
return wrapped(*args_clone, **kwargs)
```
Is causing an error to be thrown here psycopg2/_json.py:
```
def register_json(conn_or_curs=None, globally=False, loads=None,
oid=None, array_oid=None, name='json'):
if oid is None:
oid, array_oid = _get_json_oids(conn_or_curs, name)
JSON, JSONARRAY = _create_json_typecasters(
oid, array_oid, loads=loads, name=name.upper())
register_type(JSON, not globally and conn_or_curs or None) . <--------- argument 2 must be a connection, cursor or None
if …
```

Psycopg2 instrumentation breaks json registration (in aiohttp)

---

instana/meter.py

Some dynamically linked processes may not have a sys.argv available.  This PR
improves handling of such cases and also improves parsing of the command line
provided by the proc filesystem.

Improved application naming when no sys.argv

---

instana/__init__.py
instana/agent.py
instana/fsm.py
instana/hooks/hook_uwsgi.py

* Add uWSGI postfork hook support

uWSGI postfork hooks

---

instana/__init__.py
instana/log.py
instana/meter.py
instana/util.py
tests/test_secrets.py

This PR fixes a case where by for any Python process, if the gunicorn package was installed, it would default to the gunicorn logger - even if it wasn't a gunicorn process.
* Move get_proc_cmdline to util package for global use
* Use proc cmdline (when sys.argv isn't available) to see if this is a gunicorn process

Fix: Gunicorn process detection

---

instana/meter.py

Gunicorn uses the optional setproctitle package to rename processes (if it's installed).
This PR will properly name the Gunicorn process if setproctitle is not installed.

Gunicorn: Fallback if process is not renamed

---

instana/instrumentation/flask/vanilla.py
instana/instrumentation/flask/with_blinker.py
tests/apps/flaskalino.py
tests/test_flask.py

This PR adds support for Path Templates under Flask.
Flask routes such as:
```python
@app.route("/users/<username>/sayhello")
def username_hello(username):
return "<center><h1>🐍 Hello %s! 🦄</h1></center>" % username
```
will now show as grouped endpoints in Instana Analyze:
...and when drilling down:
Read more about endpoint grouping here:
https://docs.instana.io/products/application_service_management/#endpoint-grouping---path-templates

Flask: Path Templates Support

---

instana/instrumentation/pep0249.py
instana/recorder.py
tests/test_mysql-python.py
tests/test_mysqlclient.py
tests/test_psycopg2.py
tests/test_pymysql.py

Currently recorder sends db connection port within the `host` tag. This is tolerated for MySQL where port is being parsed from the host name and stored separately. However the PostgreSQL implementation behaves differently and stores the host as-is and keeps the `port` empty.
These changes unify the way postgres and mysql spans are being displayed in Instana by always sending db port separately from the host name.

Send separate 'host' and 'port' tags for MySQL/PostgreSQL tags

---

.circleci/config.yml

This PR fixes CI build for python-3.6-cassandra. These builds [currently fail](https://app.circleci.com/github/instana/python-sensor/pipelines/deaf82da-216e-49d7-b902-a4d3bc2fe73d/workflows/5ef71411-a879-4535-bb4b-49e1b0ace3ab) because of being unable to install couchbase drive due to missing header files.

Install couchbase header files while running python3.6 build on CI

---

instana/agent.py
instana/fsm.py
instana/instrumentation/aiohttp/server.py
instana/instrumentation/django/middleware.py
instana/instrumentation/flask/vanilla.py
instana/instrumentation/flask/with_blinker.py
instana/instrumentation/sqlalchemy.py
instana/instrumentation/tornado/server.py
instana/instrumentation/urllib3.py
instana/meter.py
instana/tracer.py
instana/util.py
tests/test_id_management.py
tests/test_secrets.py

Closes https://github.com/instana/python-sensor/issues/215

Address warning and deprecation messages

---

instana/instrumentation/aws/triggers.py
tests/test_lambda.py

This PR adds code to protect against unexpected values (e.g. None) in the event payload.
- Add tests to validate

AWS Lambda: Validate Query params before parsing

---

instana/agent.py
instana/fsm.py
instana/options.py
setup.py

This PR cleans up and improves the announce process.

Announce Hardiness

---

instana/__init__.py

We've updated our temp path for AutoTrace.  For the transition, this PR adds both paths for package resolution as a safety.  The deprecated path will be removed in a future version.

Add pkg_resources safety

---

instana/singletons.py

Add try block to protect against import failes from sub packages

Fix: Singleton Import Protection

---

instana/agent/aws_lambda.py
instana/collector.py
instana/instrumentation/aws/triggers.py
instana/util.py
tests/platforms/test_lambda.py

This PR fixes an issue with service mapping that can be caused by partial ARNs without the function version.

AWS Lambda: ARN Normalization

---

instana/span.py
setup.py
tests/opentracing/test_ot_span.py

With this PR, we switch to `repr` for representing objects and add more tests to validate various scenarios.
Invalid tag keys now log a DEBUG message and are discarded:
> 11:03:52 DEBUG (non-fatal) span.set_tag: tag names must be strings. tag discarded for <type 'int'>

Improved Tag Validation & Reporting

---

instana/instrumentation/aws/lambda_inst.py
instana/instrumentation/aws/triggers.py
tests/platforms/test_lambda.py

The HTTP headers are [passed in the `headers` section](https://docs.aws.amazon.com/lambda/latest/dg/services-alb.html) of event payload when a Lambda function is invoked via ELB and API Gateway, while Python sensor's Lambda instrumentation passes the whole event to the `tracer.extract()`. As a result the tract context is not being picked up, forcing each Lambda invocation to start a new trace.
In this PR `get_context()` attempts to detect the event type and pass the appropriate object to the propagator.

Fix trace context extraction in AWS Lambda

---

instana/http_propagator.py
instana/span.py
instana/tracer.py
tests/clients/test_urllib3.py
tests/data/lambda/api_gateway_event.json
tests/frameworks/test_aiohttp.py
tests/frameworks/test_django.py
tests/frameworks/test_flask.py
tests/frameworks/test_pyramid.py
tests/frameworks/test_tornado_server.py
tests/frameworks/test_wsgi.py
tests/opentracing/test_ot_propagators.py
tests/platforms/test_lambda.py

Mark HTTP calls made with `X-Instana-Synthetic` header set to `1` as synthetic by sending `span.sy: true` to the host agent for the instrumentation span.
This branch is on top of https://github.com/instana/python-sensor/pull/248 that addresses trace context extraction issue for Lambda.
@pglombardo, please note that `extract` now may return a span context without a trace ID if the synthetic call did not contain `X-Instana-{T,S}` headers. I believe the `tracer.start_span` change should address it, but I'd appreciate if you could give it a thorough view.
Closes https://github.com/instana/python-sensor/pull/231

Add synthetic calls support

---

setup.py

This PR fixes a typo in the `test-gevent` dependency list format.

Fix gevent test dependencies list format

---

instana/instrumentation/aiohttp/server.py

AIOHTTP uses some exceptions to indicate successful responses. We frequently use this for 204 / No Content APIs.
These 204s are currently showing in Instana as "Erroneous Calls", but they aren't our APIs perspective.
See https://docs.aiohttp.org/en/latest/web_exceptions.html#successful-exceptions

Don't count successful responses as errors

---

instana/__init__.py
instana/agent/aws_fargate.py
instana/agent/aws_lambda.py
instana/agent/host.py
instana/collector/helpers/runtime.py
instana/fsm.py
instana/version.py
setup.py

1. Improved package version management
2. Log boot message to host agent with package version in use
`Instana Python Package 1.25.6dev1: PID 3 (true pid: 90245) is now online and reporting`
3. New snapshot fields showing package version and instrumentation method in dashboard

RCA Helpers

---

instana/instrumentation/aws/triggers.py
tests/data/lambda/api_gateway_v2_event.json
tests/platforms/test_lambda.py

AWS has [introduced](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html) a new trigger event type, which is now a default for newly created triggers. This PR adds support for such payload format, extracting the trace context and necessary tags for the entry span.

Add support for API Gateway v2 Lambda payload

---

instana/__init__.py
instana/agent/host.py
instana/instrumentation/pika.py
instana/span.py
tests/clients/test_pika.py
tests/requirements.txt

This PR adds instrumentation for [pika](https://pypi.org/project/pika/) creating spans upon consuming and publishing from/to AMQP.

Instrument pika

---

instana/instrumentation/django/middleware.py
tests/apps/app_django.py
tests/frameworks/test_django.py

This PR updates Django instrumentation to not to count `django.http.response.Http404` exceptions as errors. This is a perfectly normal case for an app to signal that the requested document is not found, hence it should not be reported as an error.

Do not mark Django HTTP 404 response spans as errors

---

instana/instrumentation/sqlalchemy.py
instana/span.py
tests/clients/test_sqlalchemy.py
tests/requirements-27.txt

Due to Sqlalchemy updates in v.1.4 the event `dbapi_error` does not exists anymore.
```
ImportError while loading conftest '/home/circleci/repo/tests/conftest.py'.
tests/conftest.py:45: in <module>
import instana
instana/__init__.py:198: in <module>
boot_agent()
instana/__init__.py:166: in boot_agent
from .instrumentation import sqlalchemy
instana/instrumentation/sqlalchemy.py:50: in <module>
@event.listens_for(Engine, 'dbapi_error', named=True)
venv/lib/python2.7/site-packages/sqlalchemy/event/api.py:142: in decorate
listen(target, identifier, fn, *args, **kw)
venv/lib/python2.7/site-packages/sqlalchemy/event/api.py:99: in listen
_event_key(target, identifier, fn).listen(*args, **kw)
venv/lib/python2.7/site-packages/sqlalchemy/event/api.py:30: in _event_key
"No such event '%s' for target …
```

Fix: Make CI happy, sqlalchemy dbapi_error update

---

.circleci/config.yml
instana/span.py
tests/clients/test_asynqp.py

Fix: RabbitMQ check proper span type

---

instana/__init__.py

`hasattr` takes an [object](https://docs.python.org/3/library/functions.html#hasattr) and string as a parameter
Fixes #323

fix the object parameter of hasattr

---

README.md

The repository has been renamed from
https://github.com/instana/nodejs-sensor
to
https://github.com/instana/nodejs.

update repository name for Node.js

---

instana/instrumentation/aws/lambda_inst.py
instana/instrumentation/sqlalchemy.py
instana/span.py
instana/version.py

Marking the lambda call as erroneous was fixed on the 1.35.1 release but there was no error log attached. The customer would  also like to see the error log and the traceback.
Plus, added a check in the sqlalchemy instrumentation as the context can potentially be None and a customer has reported an issue because of it.

Lambda error log fix

---

tests/requirements-27.txt

Master python27 pipeline is failing because it tries to build grpcio 1.40 in python2.7 which is no longer supported

1.40 release of grpcio is no longer supporting python27

---

instana/collector/helpers/runtime.py
instana/version.py
tests/platforms/test_host_collector.py

For certain hardened runtimes, collecting metrics can trigger slow
paths in the security subsystems in place. By setting
`INSTANA_DISABLE_METRICS_COLLECTION` to `TRUE`, a customer can now
disable collecting these metrics and avoid the performance impact
that the setup causes.

Allow customers to disable metrics collection

---

instana/instrumentation/sanic_inst.py
instana/version.py
tests/apps/sanic_app/server.py
tests/frameworks/test_sanic.py

Fixing bug on evaluating args[0] even when message was present as a keyword argument and was causing an IndexError
Additional added a try/catch block to log any possible exception could be triggered by a bug in the instana code, so that this will not influence the execution flow of the customer's code.

Sanic exception bug fix

---

tests/clients/test_google-cloud-storage.py
tests/opentracing/test_ot_span.py

I just marked some tests to be skipped when they are running in Mac because they are not supported and causing false failures

added skipping of tests which fail in OSX

---

tests/apps/app_django.py
tests/clients/test_pymongo.py

Fixing some deprecated imports, they were affecting only the testing environment

Fix django urls import

---

docker-compose.yml

* Adds a few needed environment variables
* Bumps the versions of `redis` and `mongo` to the same levels used by circleci 
* Enables starting the stack with podman (Without using DNS in Container Networks)
* Minimizes the scope of shared volumes to the absolutely needed config files
* Uses the `:Z` to have the runtime label the content with a private unshared label.
* Removes unused services
* Removes outdated comments

fix(compose): Fix and modernise compose.yml

---

.circleci/config.yml
tests/requirements-asynqp-legacy-flask-markupsafe.txt
tests/requirements-asynqp.txt

* This issue is described in
https://github.com/pallets/markupsafe/issues/284
* The recommended action is to upgrade Jinja2,
https://github.com/pallets/markupsafe/issues/284#issuecomment-1044538043
but that only works with newer flask, so hence the flask upgrade.
* The exact backtrace in our case, that we are trying to avoid here is this:
```
Traceback:
/usr/local/lib/python3.7/importlib/__init__.py:127: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
tests/clients/test_asynqp.py:16: in <module>
import tests.apps.flask_app
tests/apps/flask_app/__init__.py:5: in <module>
from .app import flask_server as server
tests/apps/flask_app/app.py:10: in <module>
from flask import jsonify, Response
venv/lib/python3.7/site-packages/flask/__init__.py:14: in <module>
from …
```

fix(requirements-asynqp): Update flask to latest stable

---

.circleci/config.yml
instana/collector/base.py
instana/instrumentation/logging.py
tests/conftest.py
tests/requirements-310.txt

This PR enables the codebase to be tested on Python 3.10 in a CI loop,
so developers get fast feedback of test results on Python 3.10.

feat(ci): Add a CI test job for Python 3.10

---

instana/instrumentation/flask/vanilla.py
instana/propagators/base_propagator.py
instana/propagators/http_propagator.py
instana/recorder.py
instana/span.py
instana/span_context.py
instana/tracer.py
tests/frameworks/test_flask.py
tests/requirements-310.txt
tests/requirements.txt

* Propagate X-INSTANA-L
* Only return spans if X-INSTANA-L==0
* Only propagate span_id and trace_id if  X-INSTANA-L!=0

Handle X-INSTANA-L according to specifications

---

tests/frameworks/test_flask.py

This PR exchanges deprecated `assertEquals` to `assertEqual`,
which were introduced earlier.

fix(test): Exchange deprecated assert to non-deprecated

---

.circleci/config.yml

https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034

feat(ci): Migrate away from legacy circleci convenience images

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml

This commit adds an issue template similar to the setup of the `go-sensor` repo.

chore(github): Add issue template

---

instana/instrumentation/pika.py
instana/version.py
tests/clients/test_pika.py

Resolves #354.
Also removes duplicate call to `span.set_tag` as it seems to already be done at `_extract_broker_tags`.

Fix AttributeError when extracting tags from pika

---

instana/instrumentation/sqlalchemy.py
tests/clients/test_sqlalchemy.py
tests/conftest.py

The root cause of the AttributeError described in https://github.com/instana/python-sensor/issues/362,
appears to be a faulty assumption, that when an error occurs, the tracing must be active.
In this fix if the tracing is not active then the error event handler simply does an early return.

fix(sqlalchemy): Stand down before tracing has started (#362)

---

instana/instrumentation/django/middleware.py
instana/version.py

The old logic relied on markers placed by the decomissioned magic wand tool.
Now we base the detection on a custom path set by the injector.

fix(django): Detect running django based on the injected path

---

instana/instrumentation/flask/common.py
tests/conftest.py
tests/requirements-310.txt

* Keeps backwards compatibility with 2.1, 2.0, 1.x

Add support for Flask 2.2

---

instana/collector/helpers/runtime.py

fix: Start with an empty dict when package collection is enabled

---

instana/agent/host.py
instana/fsm.py
tests/platforms/test_host.py

* Handle scenarios gracefully, when the agent does not return an expected response
* In particular, avoid the `KeyError` scenario, which was seen in ZD 27830, because of an incomplete response:
````
File "/usr/local/lib/python3.7/site-packages/instana/agent/host.py", line 150, in set_from
self.announce_data = AnnounceData(pid=res_data['pid'], agentUuid=res_data['agentUuid'])
KeyError: 'pid'
````
* Adds test cases for covering these scenarios

Handle faulty announce responses from agents

---

tests/requirements-307.txt
tests/requirements-310-with-tornado.txt
tests/requirements-310.txt
tests/requirements.txt

Sets the minimum required version to 2.0.0 for SQLAlchemy testing
The legacy branch can still test older SQLAlchemy versions.

test: Require SQLAlchemy 2.0 for testing

---

instana/agent/host.py
tests/platforms/test_host.py

Handle `AttributeError: 'list' object has no attribute 'get'`, which has been seen in ZD 31421.

fix: Handle when the announce response has no fields

---

instana/agent/host.py
instana/version.py
tests/requirements-307.txt
tests/requirements-310.txt
tests/requirements.txt

fix: Backport handle when the announce response has no fields

---

tests/frameworks/test_aiohttp_client.py
tests/frameworks/test_aiohttp_server.py
tests/frameworks/test_tornado_server.py
tests/requirements-307.txt
tests/requirements-310-with-tornado.txt
tests/requirements-310.txt
tests/requirements.txt

Apparently the parameter passing in our `aiohttp` tests were incorrect, and was depending on a `yarl` bug [1] that was fixed [2] in `1.9.0`, and with this new yarl version, our tests started to fail. This fix corrects the parameter passing, so we can use the latest `yarl`.
[1] https://github.com/aio-libs/yarl/issues/723
[2] https://github.com/aio-libs/yarl/pull/792

test[fix]: Pass parameters to aiohttp correctly

---

instana/w3c_trace_context/traceparent.py
tests/frameworks/test_django.py
tests/propagators/test_http_propagator.py
tests/w3c_trace_context/test_traceparent.py

The W3C trace context specification mandates that a participant must only send known flags downstream. See
https://www.w3.org/TR/trace-context/#other-flags: "The behavior of other flags, such as (00000100) is not defined and is reserved for future use. Vendors MUST set those to zero."

fix(w3c trace context): do not pass down unknown flags.

---

instana/instrumentation/flask/with_blinker.py
tests/clients/test_urllib3.py

Removes a `TODO` item, and re-enables the assertion of the status code being `500` on the `wsgi` span.

fix(blinker): Always set 500 on exception signal

---

instana/w3c_trace_context/traceparent.py
tests/w3c_trace_context/test_traceparent.py

This is a follow up to commit
f283a4beb4d2b7ccb9b5aae55d076c7a5156e1d0
which added some tests for parsing newer versions. One of the tests used format version "ff", which the W3C trace context specification explicitly defines as invalid. This commit fixes that test and also the regex used for parsing the traceparent header, so that a header with version ff will be rejected as invalid.

fix(w3c trace context): consider traceparent format version ff invalid

---

instana/agent/host.py
tests/platforms/test_host.py

The check for the Server header of the Instana agent can break the announce procedure in service meshes when there is a proxy between the tracer and the Instana agent. This happens because some proxies do not forward the original Server header. So instead, the collector checks whether the HTTP status code is in the 2xx range.

Fix: remove the check for the Server header of the Instana agent.

---

tests/clients/test_mysqlclient.py
tests/clients/test_psycopg2.py
tests/clients/test_pymysql.py

Add context manager tests to db modules that conform to PEP-249
- psycopg2
- pymysql
- mysqlclient

Add ctx manager tests for pep249 based db modules

---

tests/clients/test_mysqlclient.py
tests/clients/test_psycopg2.py
tests/clients/test_pymysql.py

* Use the `unittest` module's `assert` in unit tests.
* Drop legacy branching for unsupported 2.7
* Eliminate unused variables
* Remove superfluous initializations
* Use unpack assignments

refactor(tests): Clean up old PEP-249 tests

---

instana/instrumentation/pep0249.py
tests/clients/test_psycopg2.py
tests/clients/test_pymysql.py

This PR contains two commits.
The first one, https://github.com/instana/python-sensor/commit/55e826e81ff311cefac112cd0d1fa4b111c91f23, adds `dbname` as a collecting parameter for PEP0249. When connecting to a PostgreSQL server, for example, using the psycopg2 module, the parameter `dbname` can be used to specify the database name to connect into, like the following piece of code:
```python
conn = psycopg2.connect(
host=os.environ['POSTGRES_HOST'],
dbname=os.environ['POSTGRES_DB'],
user=os.environ['POSTGRES_USER'],
password=os.environ['POSTGRES_PASSWORD']
)
```
Without this fix, the Instana UI is not able to display the database name when inspecting an EXIT span, as shown in the following image:
With this fix, the name of the database is collected and displayed:
The second commit, 221432e, …

Add `dbname` as collecting parameter for PEP0249

---

instana/agent/host.py
instana/collector/base.py

In multithreaded applications (services), only the first or master process is announced to the Agent when the service starts, but if a not announced forked process handles the (HTTP) ENTRY requests and it contains one or more EXIT spans created during the first request, those EXIT spans are missed and not reported. 
This PR has a fix that returns `True` when the `agent.host.can_send()` method is called and detects the state machine is in `wait4init` or `good2go` states, which happens after the current process is announced to the Agent.

Fork missing spans fix

---

instana/collector/base.py

This PR solves the issue of the background report thread not releasing the lock when the application is manually instrumented and runs with multiple workers (uWSGI).

refactor: Using context manager to handle threading.Lock

---

setup.py
tests/requirements-307.txt
tests/requirements-310-with-tornado.txt
tests/requirements-310.txt
tests/requirements-312.txt
tests/requirements-cassandra.txt
tests/requirements-gevent.txt
tests/requirements.txt

Signed-off-by: Varsha GS varsha.gs@ibm.com
- Use urllib3>=1.26.18
- Remove secure extra feature ([more info](https://github.com/urllib3/urllib3/issues/2680))

Use latest urllib3 without secure extra

---

tests/conftest.py

Unskip boto3_secretsmanager test case on python>=3.10

ci: Unskip boto3_secretsmanager TC on python>=3.10

---

instana/instrumentation/aiohttp/client.py
instana/instrumentation/aiohttp/server.py
instana/instrumentation/asgi.py
instana/instrumentation/django/middleware.py
instana/instrumentation/fastapi_inst.py
instana/instrumentation/flask/common.py
instana/instrumentation/flask/vanilla.py
instana/instrumentation/flask/with_blinker.py
instana/instrumentation/pyramid/tweens.py
instana/instrumentation/sanic_inst.py
instana/instrumentation/tornado/server.py
instana/instrumentation/urllib3.py
instana/instrumentation/wsgi.py

Quote from the [spec](
https://github.ibm.com/instana/technical-documentation/tree/master/tracing/specification#capturing-errors-on-http-spans):
> For HTTP exit and entry spans alike, if a full request/response cycle has happened (which implies that an HTTP status code is present): If the HTTP status code is >= 500, the associated span MUST be marked as an error via span.ec.
This means that there is no upper limit, and this should apply to custom status codes as well, which might be above `511`, or even `599`.

fix: The spec doesn't set upper limit for ec=1 if code>=500

---

instana/instrumentation/django/middleware.py
tests/apps/app_django.py
tests/frameworks/test_django.py

Django: capture responseHeadersOnEntrySpans
Signed-off-by: Varsha GS [varsha.gs@ibm.com](mailto:varsha.gs@ibm.com)

Django: capture responseHeadersOnEntrySpans

---

instana/instrumentation/asgi.py
tests/apps/fastapi_app/__init__.py
tests/apps/fastapi_app/app.py
tests/frameworks/test_fastapi.py

FastAPI: capture responseHeadersOnEntrySpans

FastAPI: capture responseHeadersOnEntrySpans

---

instana/instrumentation/flask/common.py
instana/instrumentation/flask/vanilla.py
instana/instrumentation/flask/with_blinker.py
tests/apps/flask_app/app.py
tests/frameworks/test_flask.py

Flask: capture responseHeadersOnEntrySpans
Signed-off-by: Varsha GS [varsha.gs@ibm.com](mailto:varsha.gs@ibm.com)

Flask: capture responseHeadersOnEntrySpans

---

instana/instrumentation/urllib3.py
tests/clients/test_urllib3.py

urllib3: capture requestHeadersOnExitSpans

urllib3: capture requestHeadersOnExitSpans

---

instana/instrumentation/boto3_inst.py
tests/clients/boto3/test_boto3_lambda.py
tests/clients/boto3/test_boto3_s3.py
tests/clients/boto3/test_boto3_secretsmanager.py
tests/clients/boto3/test_boto3_ses.py
tests/clients/boto3/test_boto3_sqs.py

Enhance boto3 instrumentation to capture HTTP headers in all four flavours
- [Kanbanize Card](https://instana.kanbanize.com/ctrl_board/197/cards/150067/details/)
According to [our spec](https://github.ibm.com/instana/technical-documentation/tree/master/tracing/specification#capturing-headers-on-http-spans), tracers SHOULD capture all four flavours of HTTP headers.

Enhance boto3 instrumentation to capture HTTP headers in all four flavours

---

docker-compose.yml
tests/requirements-310-with-tornado.txt

This PR contains two commits to refector and improve our code:
1. The first guarantee container images always come from the Docker registry. That prevents that podman, for example, running in RHEL systems, from downloading images from other registries.
2. To reduce the maintenance of the requirements used in our tests, this fix refers to other requirement files that have the same list of packages.

Refectoring and improvements

---

instana/instrumentation/sanic_inst.py
instana/util/traceutils.py
tests/apps/sanic_app/__init__.py
tests/apps/sanic_app/server.py
tests/frameworks/test_sanic.py

Sanic: capture responseHeadersOnEntrySpans

Sanic: capture responseHeadersOnEntrySpans

---

instana/instrumentation/tornado/server.py
tests/apps/tornado_server/__init__.py
tests/apps/tornado_server/app.py
tests/frameworks/test_tornado_server.py

tornado_server: capture responseHeadersOnEntrySpans
Signed-off-by: Varsha GS [varsha.gs@ibm.com](mailto:varsha.gs@ibm.com)

Tornado Server: capture responseHeadersOnEntrySpans

---

tests/apps/fastapi_app/app.py
tests/frameworks/test_fastapi.py

Add a non-async path operation function that makes a complex non-asynchronous request to check if all the outgoing calls made by the request are properly traced.

[FastAPI] Add TC for non-async methods

---

.circleci/config.yml
.tekton/github-pr-pipeline.yaml.part
.tekton/pipeline.yaml
.tekton/run_unittests.sh
.tekton/task.yaml
tests/__init__.py
tests/apps/aiohttp_app/__init__.py
tests/apps/grpc_server/__init__.py
tests/apps/tornado_server/__init__.py
tests/conftest.py
tests/frameworks/test_gevent.py
tests/requirements-gevent-starlette.txt

Run both starlette and gevent tests together in a single job
[PR](https://github.com/tiangolo/fastapi/pull/11146/files) from FastAPI to include the latest starlette version is still not merged
slack thread: https://instana.slack.com/archives/C05M4RNDPLZ/p1709204882315999

ci: Include testing with latest starlette version

---

src/instana/version.py

New feature going into `2.4.0`: Add opt-in root exit spans

chore(version): Bump version to 2.4.0

---

.tekton/.currency/currency-scheduled-eventlistener.yaml
.tekton/.currency/currency-tasks.yaml

- [skip push and exit pipeline when report generation fails](https://github.com/instana/python-sensor/commit/c4c4afce1426c3555208b640eedf788b4b18a121)
- [schedule the currency pipeline to run 15 mins after the CI pipeline](https://github.com/instana/python-sensor/commit/65a5c053925e2a2289697691ffac3336ea44f69e)

currency: Fix currency report overwrite

---

src/instana/instrumentation/gevent_inst.py

If the `gevent` module is not installed,
but there is a directory called `gevent`
or a `gevent.py` file in the current directory,
then that is already importable and the statment
`if sys.modules['gevent'].version_info < (1, 4):`
fails with
`AttributeError: module 'gevent' has no attribute 'version_info'`
This can happen easily since many libraries like `celery`, `grpc`, `opentracing` etc, deliver their own file called `gevent.py`.

fix: Prevent crash with 'gevent' has no attribute 'version_info'

---

src/instana/collector/helpers/runtime.py
tests/platforms/test_host_collector.py

So do not look for the sideffects of the removed injector.

fix: Set AutoTrace method when the webhook is active

---

.circleci/config.yml
pytest.ini
src/instana/collector/helpers/runtime.py
src/instana/collector/host.py
src/instana/propagators/base_propagator.py
src/instana/tracer.py
src/instana/util/traceutils.py
src/instana/w3c_trace_context/traceparent.py
src/instana/w3c_trace_context/tracestate.py
tests/conftest.py
tests/requirements-310.txt
tests/requirements-312.txt
tests/requirements-313.txt
tests/requirements.txt
tests/test_span.py
tests/test_tracer.py

Based on changes made on #550. 
Adapt the following to OTel specifications, and fix some rebasing issues:
- inject()
- extract()
- traceparent
- tracestate
- get_current_span()
- get_active_tracer()
- get_tracer_tuple()
Signed-off-by: Varsha GS [varsha.gs@ibm.com](mailto:varsha.gs@ibm.com)
Co-authored-by: Paulo Vital [paulo.vital@ibm.com](mailto:paulo.vital@ibm.com)

(new) Adapt common utilities to OTel specifications.

---

src/instana/span/base_span.py
src/instana/span/readable_span.py
src/instana/span/span.py
src/instana/tracer.py
tests/test_span.py

- style: Update type hints.
- Use Type["BaseAgent"] instead of a long Union list with all its inherited classes.
- Update the return type hint for the Span duration property.
- fix(tests): Add Span duration unit tests.
- Add new tests to cover the changes on the (readable)span duration property.
- Fix the Span duration update when ending a Span.

OTel small fixes.

---

src/instana/collector/aws_eks_fargate.py
src/instana/collector/aws_fargate.py
src/instana/collector/aws_lambda.py
src/instana/collector/google_cloud_run.py
src/instana/collector/host.py
src/instana/collector/utils.py
src/instana/span/registered_span.py
tests/test_span_registered.py

Fix the below error that hinders reporting tracer data to the agent.
```
2024-07-15 12:41:31,430: 51725 DEBUG instana: to_json non-fatal encoding issue: 
File "/Users/varsha/Documents/GitHub/instana-repos/tracer-repos/python-sensor/src/instana/util/__init__.py", line 36, in to_json
return json.dumps(obj, default=extractor, sort_keys=False, separators=(',', ':')).encode()
File "/Users/varsha/.pyenv/versions/3.9.7/lib/python3.9/json/__init__.py", line 234, in dumps
return cls(
File "/Users/varsha/.pyenv/versions/3.9.7/lib/python3.9/json/encoder.py", line 199, in encode
chunks = self.iterencode(o, _one_shot=True)
File "/Users/varsha/.pyenv/versions/3.9.7/lib/python3.9/json/encoder.py", line 257, in iterencode
return _iterencode(o, 0)
```
`span.k` was of …

fix: Report data to agent

---

pyproject.toml
src/instana/tracer.py

The new OTel API version 1.26.0 introduces changes to the `TracerProvider.get_tracer()`, which must be reflected in our code.

fix: TracerProvider.get_tracer() after API update.

---

tests/requirements-310.txt
tests/requirements-312.txt
tests/requirements-313.txt
tests/requirements.txt

There is a common issue with the last version of setuptools. It looks like they've removed the test attribute from setuptools.command module. I found a solution from the Github issue below and implemented it to our pipeline.
It's because of a package named spyne: https://github.com/arskom/spyne
It's not being updated for a long time (7 months), has some conflicts with setuptools
https://github.com/pypa/setuptools/issues/4519

Added constraint for setuptools Python module

---

src/instana/span/registered_span.py
tests/clients/test_logging.py
tests/test_span_registered.py

Log message >WARN not showing up in the UI
Revert `span.data["event"]` to `span.data["log"]`

fix: log message >WARN not showing up in the UI

---

src/instana/tracer.py
tests/test_tracer.py
tests/test_tracer_provider.py

The trace is malformed and contains multiple root calls: [link](https://instana.rocks/s/b5H7hsYFSwavGPBy59rcIQ)
```
127.0.0.1 - - [30/Jul/2024 13:23:34] "GET /users/5 HTTP/1.1" 200 -
2024-07-30 13:23:34,444: 64371 DEBUG instana: Reporting 2 spans
1 - Trace ID: 04c06e2c65ecc0eb  Span ID: 0bf364bca4dfac96       Span Name: urllib3
2 - Trace ID: 04c06e2c65ecc0eb  Span ID: 04c06e2c65ecc0eb       Span Name: wsgi
foo bar
127.0.0.1 - - [30/Jul/2024 13:23:38] "GET /users/ HTTP/1.1" 200 -
2024-07-30 13:23:38,441: 64371 DEBUG instana: Reporting 3 spans
1 - Trace ID: 04c06e2c65ecc0eb  Span ID: 997a95ffb37bf2ff       Span Name: log
2 - Trace ID: 04c06e2c65ecc0eb  Span ID: c29c6688592d996f       Span Name: urllib3
3 - Trace ID: 04c06e2c65ecc0eb  Span ID: 04c06e2c65ecc0eb       Span Name: wsgi
127.0.0.1 …
```

fix: The trace is malformed and contains multiple root calls

---

src/instana/__init__.py
tests/conftest.py

Add logic to enable the instrumentation tests as their migration is finalized. 
In addition, formated the `__init__.py` file and fixed lint violations, using `ruff` (vscode) to:
- Black-compatible code formatting.
- fix all auto-fixable violations, like unused imports.
- isort-compatible import sorting.

[OTel] enable instrumentation tests

---

pyproject.toml
src/instana/version.py

Before commit `c222d96`, the `setup.py` contained the following entry point specification:
````
entry_points={
'instana':  ['string = instana:load'],
````
And **entrypoints** are a must have when using `autowrapt`. 
Quote from the [autowrapt documentation](
https://github.com/GrahamDumpleton/autowrapt/blob/d4770e4f511c19012055deaab68ef0ec8aa54ba4/README.rst?plain=1#L11 ):
> list the names of the setuptools **entrypoints** you wish to activate
This can also be observed in the calls made by `autowrapt`:
````
<frozen importlib._bootstrap>(991)_find_and_load()
<frozen importlib._bootstrap>(975)_find_and_load_unlocked()
<frozen importlib._bootstrap>(671)_load_unlocked()
<frozen importlib._bootstrap_external>(843)exec_module()
<frozen importlib._bootstrap>(219)_call_with_frames_removed() …
```

fix: Re-enable activation without codechange (`AUTOWRAPT_BOOTSTRAP=instana`)

---

src/instana/tracer.py
tests/test_tracer.py

Fix: context propagation in nested spans

Fix: context propagation in nested spans

---

src/instana/propagators/base_propagator.py
src/instana/tracer.py
tests/frameworks/test_flask.py
tests/frameworks/test_wsgi.py

Handle instana trace suppression.

Fix: Handle instana trace suppression

---

tests/clients/test_urllib3.py

Replace `httpbin.org/robots.txt` with `reqres.in/api/users`

fix: Flaky test in urllib3

---

src/instana/instrumentation/logging.py
tests/clients/test_logging.py

log_with_instana -> \_\_call__ -> custom_func
`stacklevel1 -> stacklevel2 -> stacklevel3`
log_with_instana -> custom_func
`stacklevel1 -> stacklevel2`
Bug reported by a customer: https://github.com/instana/python-sensor/issues/563
```
BEFORE instana import
funcName:custom_func message:Hello, world
AFTER instana import
funcName:log_with_instana message:Hello, world
```
```
BEFORE instana import
funcName:custom_func message:Hello, world
AFTER instana import
funcName:custom_func message:Hello, world
```

fix: Capture the correct log caller

---

tests/clients/test_logging.py

- fix: Adapt logging tests to OTel after rebase.
- tests(logging): Refactor to pure pytest UT.

Fix OTel logging tests

---

src/instana/__init__.py
src/instana/instrumentation/pymysql.py
src/instana/span/registered_span.py
tests/clients/test_pymysql.py
tests/conftest.py

[OTel] Refactor of pymysql implementation

---

src/instana/__init__.py
src/instana/instrumentation/pymongo.py
src/instana/span/registered_span.py
tests/clients/test_pymongo.py
tests/conftest.py
tests/test_tracer_provider.py

[OTel] Refactor of Pymongo insrumentation

---

src/instana/__init__.py
src/instana/instrumentation/couchbase_inst.py
tests/clients/test_couchbase.py
tests/conftest.py

[OTel] Refactor couchbase instrumentation

---

src/instana/__init__.py
src/instana/instrumentation/cassandra_inst.py
tests/clients/test_cassandra-driver.py
tests/conftest.py

[OTel] Refactor cassandra instrumentation

---

src/instana/__init__.py
src/instana/instrumentation/redis.py
tests/clients/test_redis.py
tests/conftest.py
tests/helpers.py

[OTel] Refactor redis instrumentation

---

src/instana/__init__.py
src/instana/instrumentation/pika.py
tests/clients/test_pika.py
tests/conftest.py

[OTel] Pika instrumentation

---

src/instana/propagators/base_propagator.py
src/instana/w3c_trace_context/traceparent.py
tests/conftest.py
tests/propagators/test_binary_propagator.py
tests/propagators/test_http_propagator.py

- Fixed propagators and traceparent files to work after OTel migration, following the OTel and W3C specifications.
- TODO later:
- Adapted propagators and w3c files to follow new style guidelines.
- Coverage will be handled later.

[OTel] Guarantee propagators tests after OTel migration.

---

src/instana/span/base_span.py
tests/frameworks/test_flask.py
tests/span/test_base_span.py

Related to https://github.com/instana/python-sensor/pull/612.
- Update the respective tests.

fix: Remove an unsupported top level span attribute.

---

tests/frameworks/test_tornado_server.py

tornado_server: skip flaky tests (405, 500, 505)

tornado_server: skip flaky tests

---

src/instana/instrumentation/couchbase_inst.py
src/instana/instrumentation/sanic_inst.py
src/instana/span/sdk_span.py
tests/span/test_span_sdk.py

- fix(sanic): capture headers only if `agent.options.extra_http_headers` is `True`
- fix(sanic): skip instrumentation for unsupported versions
- fix(couchbase): fix skipping instrumentation for unsupported versions. Earlier, it would fail even if `couchbase` does not have `__version__` attribute.
- minor fix(couchbase): skip importing other modules if the package to be instrumented is not present
- fix: capture custom tags on SDK spans: https://github.ibm.com/instana/technical-documentation/tree/master/tracing/specification#span-data

[OTel] Fix `sanic` headers capture, `couchbase` imports, `sdk.custom.tags`

---

tests/span/test_span.py

This PR is needed for Celery instrumentation, solves the test_span unittest errors
- Added logger configurations to catch Status class logs using caplog 
- Made some format enhancement and typing annotations
- Restructured unittests using TestSpan class

[OTel] Fix: test_span caplog setup

---

src/instana/__init__.py
src/instana/instrumentation/google/cloud/pubsub.py
src/instana/instrumentation/google/cloud/storage.py
tests/clients/test_google-cloud-pubsub.py
tests/clients/test_google-cloud-storage.py
tests/conftest.py

- Pubsub coverage: 90%
- Cloud Storage coverage: 91%

[OTel] PubSub & Cloud Storage instrumentation

---

tests/clients/test_cassandra-driver.py

- Cassandra unittests were failing due to flaky assert conditions

[OTel] cassandra unittest fix

---

.tekton/pipeline.yaml
.tekton/run_unittests.sh

Fix the below syntax error on Tekton CI: 
`/workspace/python-sensor/.tekton/run_unittests.sh: line 50: syntax error near unexpected token ')'`

fix(ci): Tekton specific errors

---

tests/conftest.py
tests/span/test_span.py

Part 2 of https://github.com/instana/python-sensor/pull/643.

Fix: Flaky tests (Part 2)

---

src/instana/__init__.py
src/instana/hooks/hook_gunicorn.py

Added gunicorn hook support and tested using fast api on ubuntu.

[OTel] gunicorn: Gunicorn Hook Support

---

src/instana/instrumentation/logging.py
tests/clients/test_logging.py

The error `_log() got multiple values for keyword argument 'stacklevel'` may occur when you pass both a positional argument and a keyword argument with the same name (`stacklevel`) to the `Logger._log()` function.
This fix checks if the `stacklevel` is a key of the `kwargs` dictionary before calling the `Logger._log()` function, considering it if present.

fix: _log() Multiple Values for 'stacklevel'.

---

src/instana/collector/utils.py
src/instana/instrumentation/aws/lambda_inst.py
src/instana/propagators/base_propagator.py
src/instana/propagators/http_propagator.py
src/instana/span/base_span.py
src/instana/tracer.py
src/instana/util/ids.py
src/instana/w3c_trace_context/traceparent.py
tests/frameworks/test_flask.py
tests/propagators/test_http_propagator.py
tests/span/test_base_span.py
tests/w3c_trace_context/test_traceparent.py
tests_aws/01_lambda/test_lambda.py

Fix: Adapt to instana spec on HTTP span processing

---

src/instana/instrumentation/django/middleware.py

Fix: Provide ASGI support with Django.
`request.environ` is available only with requests of type `WSGIRequest` and not `ASGIRequest`.
[`request.headers`](https://docs.djangoproject.com/en/3.0/ref/request-response/#django.http.HttpRequest.headers) is only available from `django-2.2`.
Since we provide support for `django>=1.11` we'll use [`request.META`](https://docs.djangoproject.com/en/5.1/ref/request-response/#django.http.HttpRequest.META).

fix: provide ASGI support with Django

---

src/instana/instrumentation/logging.py
tests/clients/test_logging.py

Related to https://github.com/instana/python-sensor/pull/652
Bypass the stack level of our instrumentation when the keyword `stacklevel` is set as well.
log_with_instana -> log_custom_warning -> main
`stacklevel1 -> stacklevel2 -> stacklevel3`
log_custom_warning -> main -> test_log_caller_with_stacklevel
`stacklevel1 -> stacklevel2 -> stacklevel3`

Adapt to logger's incoming stacklevel

---

.circleci/config.yml
.tekton/pipeline.yaml
.tekton/run_unittests.sh
tests/conftest.py

Run only starlette tests for now in `gevent_starlette` task

Fix(currency): Run only starlette tests in `gevent_starlette` task

---

src/instana/util/ids.py
tests_aws/01_lambda/test_lambda.py

Failure scenarios: [case-1](https://app.circleci.com/pipelines/github/instana/python-sensor/3374/workflows/4b6ccede-4ff2-43e6-b1e3-a5df87b70c6f/jobs/24244/tests#failed-test-0) with trace_id, [case-2](https://app.circleci.com/pipelines/github/instana/python-sensor/3362/workflows/f269fb28-b8c8-4fef-a721-d73baf01da6d/jobs/24064/tests#failed-test-0) with parent relationship (parent_id, span_id)
Considering cases when the hexadecimal string contains all the characters as digits.
```
>>> id=8360669476235335784
>>> hexid=hex(id)[2:]
>>> hexid
'7407109787755868'
>>> hexid.isdigit()
True
```

Fix flaky tests with inconsistent trace and span ids

---

.github/CODEOWNERS

Adding GitHub [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) file to extend branch protection on the repo.

chore: Add GitHub CODEOWNERS file.

---

.github/workflows/pr_commits_signed_off.yml
.github/workflows/sonarqube.yml
.tekton/.currency/currency-pipelinerun.yaml
.tekton/.currency/currency-scheduled-eventlistener.yaml
.tekton/README.md
.tekton/github-pr-pipeline.yaml.part
.tekton/scheduled-eventlistener.yaml
README.md
RELEASE.md

Post work after the branch `master` has been renamed to `main`.

fix: post branch rename changes

---

bin/aws-lambda/build_and_publish_lambda_layer.py

- fix: add new aws region `ap-southeast-5` to publish
- style: Migrate from old-style `%s` to f-strings

Update lambda publish script

---

src/instana/instrumentation/django/middleware.py
tests/requirements.txt

- Add support to ASGI requests.
- Migrate the Django middleware to conform with the new style, from Django 2.0 onwards. By having a single entrypoint to the middleware, \_\_call__, which is [wrapped with sync_to_async just once](https://github.com/django/django/blob/213850b4b9641bdcb714172999725ec9aa9c9e84/django/core/handlers/base.py#L54-L57) for async requests, we avoid the [issue](https://github.com/django/asgiref/issues/267) where a ContextVar cannot be reset from a different context.
ASGI support new in [3.0](https://docs.djangoproject.com/en/5.1/releases/3.0/#what-s-new-in-django-3-0)
`response.headers` new in [3.2](https://docs.djangoproject.com/en/3.2/ref/request-response/#django.http.HttpResponse.headers) (needed to extract custom headers)

Fix(django): Support ASGI requests

---

bin/aws-lambda/build_and_publish_lambda_layer.py

Improve AWS Lambda Layer build script

---

.circleci/config.yml
.tekton/.currency/currency-scheduled-eventlistener.yaml
.tekton/.currency/currency-tasks.yaml
.tekton/github-pr-pipeline.yaml.part
.tekton/github-set-status-task.yaml
.tekton/pipeline.yaml
.tekton/python-tracer-prepuller.yaml
.tekton/run_unittests.sh
.tekton/scheduled-eventlistener.yaml
.tekton/task.yaml
Dockerfile
docker-compose.yml
tests/clients/test_google-cloud-pubsub.py

This PR:
1. Remove the Couchbase tests from the CI pipeline and 
2. Change the development files and CI configuration to stop pulling container images from the Docker Hub.

Not pull container images from Docker Hub

---

.circleci/config.yml
.tekton/pipeline.yaml
.tekton/python-tracer-prepuller.yaml
.tekton/run_unittests.sh
src/instana/instrumentation/logging.py
tests/clients/test_google-cloud-storage.py
tests/conftest.py
tests/requirements-pre314.txt

Add the new alpha2 test build for Python 3.14.0 after being announced [here](https://www.python.org/downloads/release/python-3140a2/).

ci: Add new pipeline to test Python 3.14.0a2.

---

.circleci/config.yml

Updated circleci pipeline to provide filtering src, tests and tests_aws folders before running the pipeline.
Added exception for nightly builds of the main

ci: updated pipeline to filter src, tests and tests_aws folders

---

tests/requirements.txt

This change fixes [this](https://app.circleci.com/pipelines/github/instana/python-sensor/3602/workflows/b7416b9b-07d5-4b6e-831d-611ef8ec96d9/jobs/26300/parallel-runs/0/steps/0-103) CI error for `python38` job.
Reference: https://github.com/sanic-org/sanic/pull/3020

fix(sanic): remove 3.8 support for latest versions

---

.circleci/config.yml
.tekton/pipeline.yaml
.tekton/python-tracer-prepuller.yaml

ci: Add support for latest runtime version 3.14.0a3

ci: Add support for latest runtime version 3.14.0a3

---

.github/workflows/pkg_release.yml

This commit adds automation to release and publish into GitHub and PyPI.org any new package version based on the creation of a new tag.

ci: Automate package release and publish.

---

src/instana/util/traceutils.py

```
2025-01-20 20:18:39,760: 71181 DEBUG instana: Agent is ready.  Getting to work.
2025-01-20 20:19:09,467: 71181 DEBUG instana: Flask(blinker): Applying flask before/after instrumentation funcs
2025-01-20 20:19:09,469: 71181 DEBUG instana: extract_custom_headers: 
File "/Users/varsha/Documents/GitHub/tracer-repos/python-sensor-example-flask/.venv/lib/python3.9/site-packages/instana/util/traceutils.py", line 18, in extract_custom_headers
for custom_header in agent.options.extra_http_headers:
TypeError: 'NoneType' object is not iterable
127.0.0.1 - - [20/Jan/2025 20:19:09] "GET / HTTP/1.1" 200 -
2025-01-20 20:19:09,747: 71181 DEBUG instana: Reporting 1 spans
```
```
2025-01-20 20:43:04,924: 76086 DEBUG instana: Agent is ready.  Getting to work. …
```

fix: capture headers

---

.tekton/pipeline.yaml
.tekton/python-tracer-prepuller.yaml

```
Configuration is 'default' on 3.14.0a3 with dependencies in 'requirements-pre314.txt'
```
```
Configuration is 'default' on 3.14.0a4 with dependencies in 'requirements-pre314.txt'
```

fix: use the correct image for 3.14.0a4

---

src/instana/agent/host.py
src/instana/collector/helpers/runtime.py
src/instana/options.py
src/instana/util/config.py
src/instana/util/traceutils.py
tests/agent/test_host.py
tests/clients/test_redis.py
tests/util/test_config.py
tests/util/test_traceutils.py

Added endpoint filtering for redis instrumentation. We've aligned with Java and NodeJS teams. The customer has three options to filter endpoints:
- Defining ignore-endpoint through the configuration.yaml file of the agent
- Using environment-variable before initialisation
- Using src/instana/configurator.py
If the customer used more than one way of these three, we'd be using one according to this priority:
- Environment variable > in-code setting > agent configuration
The customer can use filtering with the environment variable below. If the env variable is set, other two ways will be ignored.
- `INSTANA_IGNORE_ENDPOINTS="service:endpoint"`
- `INSTANA_IGNORE_ENDPOINTS="service:endpoint1,endpoint2"`
- Filtering redis instrumentation at all:
`INSTANA_IGNORE_ENDPOINTS="service"`
- Filtering …

[FUP Optimisation] redis: added endpoint filtering

---

src/instana/instrumentation/asgi.py
src/instana/instrumentation/pep0249.py
src/instana/instrumentation/pyramid.py
src/instana/instrumentation/sanic_inst.py
src/instana/span/registered_span.py
tests/clients/test_pep0249.py
tests/span/test_registered_span.py

Remove unsupported redundant span attribute `span.data.custom.attributes`
```
{"data":{...,"custom":{"attributes":{"span.kind":"<SpanKind.SERVER: 1>"}}},...}
```

fix: remove unsupported span attribute

---

.circleci/config.yml
.tekton/pipeline.yaml
.tekton/python-tracer-prepuller.yaml

ci: Add support to test Python 3.14.0a5.

---

.gitignore

chore: Ignore uv.lock file on Git.

---

src/instana/agent/host.py
src/instana/options.py
tests/test_options.py

Added extra-http-headers support to tracer's agent configuration headers.
https://www.ibm.com/docs/en/instana-observability/current?topic=cha-configuring-host-agents-by-using-agent-configuration-file#capturing-custom-http-headers

fix: capturing extra-http-headers from agent config

---

.tekton/.currency/docs/report.md
.tekton/.currency/scripts/generate_report.py

Added new columns to currency report:
- Latest Version Published At
- Days Behind
| Package name         | Support Policy   | Beta version   | Last Supported Version   | Latest version   | Up-to-date   | Release date   | Latest Version Published At   | Days behind   | Cloud Native   |
|:---------------------|:-----------------|:---------------|:-------------------------|:-----------------|:-------------|:---------------|:------------------------------|:--------------|:---------------|
| ASGI                 | 45-days          | No             | 3.0                      | 3.0              | Yes          | 2019-03-04     | 2019-03-04                    | 0 day/s       | No             |
| Celery               | 45-days          | No             | 5.4.0                    | 5.4.0 …

currency: added release date and days behind support

---

src/instana/instrumentation/pika.py

Test_consume case was failing due to the break inside __consume function. When we break the for loop, generator propagates GeneratorExit exception. I've added an exception case and closed the generator gracefully.

fix: added exception for pika consumer

---

src/instana/__init__.py
src/instana/instrumentation/spyne.py
tests/apps/spyne_app/__init__.py
tests/apps/spyne_app/app.py
tests/conftest.py
tests/frameworks/test_spyne.py
tests/requirements.txt

feat: Add Spyne instrumentation

feat: Add Spyne instrumentation

---

src/instana/instrumentation/kafka/kafka_python.py
tests/clients/kafka/test_confluent_kafka.py
tests/clients/kafka/test_kafka_python.py

Add instrumentation support for the `KafkaConsumer.poll()` and make the `confluent-kafka.poll()` test faster.

Improve kafka-python

---

src/instana/propagators/base_propagator.py

- `sanic.compat.Header` contains `__dict__` attribute but does not store the headers dictionary in it. Hence directly convert the `CIMultiDict` instance to dictionary using `dict()`.

fix(sanic): Handle headers extraction after `multidict` update

---

.circleci/config.yml

Circle CI pipelines were failing for Python 3.9-3.10-3.11 versions due to the last version of `wheels` package. This PR temporarily fixes the issue until a new version of the Wheels package is released.
Main Pipeline

ci: downgrade wheel package version

---

.circleci/config.yml
.tekton/.currency/currency-tasks.yaml
.tekton/pipeline.yaml
.tekton/python-tracer-prepuller.yaml

The Python-3.14.0a7 (together with 3.13.3, 3.12.10, 3.11.12, 3.10.17 and 3.9.22) was released on April 8th, 2025.

CI: Bump up Python version for automated tests.

---

.circleci/config.yml
pytest.ini
tests/requirements-aws.txt
tests/requirements-minimal.txt
tests_autowrapt/test_autowrapt.py

Only checking if `instana` is present in `sys.modules` and not explicitly recording/checking if any spans are recorded because any import like `from instana.<module> import <method>` loads auto-instrumentation [here](https://github.com/instana/python-sensor/blob/main/src/instana/__init__.py#L255) and hence failing the purpose of the intended tests.

Add tests to verify activating the tracer without code changes

---

src/instana/options.py
tests/test_options.py

This PR fixes the TypeError of non-dict response data from Agent announcement.
```
tests/clients/kafka/test_confluent_kafka.py::TestConfluentKafka::test_trace_confluent_kafka_produce
/root/repo/venv/lib/python3.12/site-packages/_pytest/threadexception.py:82: PytestUnhandledThreadExceptionWarning: Exception in thread Instana Machine
File "/usr/local/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.12/threading.py", line 1433, in run
self.function(*self.args, **self.kwargs)
File "/root/repo/venv/lib/python3.12/site-packages/fysom/__init__.py", line 315, in fn
self.transition()
File "/root/repo/venv/lib/python3.12/site-packages/fysom/__init__.py", line 310, in _tran
self._after_event(e)
File …
```

Fix TypeError of non-dict response data from Agent announcement.

---

tests/clients/test_urllib3.py

The old service (Reqres) started to require an API key on the 25th of April

fix: change request url for urllib

---

docker-compose.yml

```
WARN[0000] /python-sensor/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, 
please remove it to avoid potential confusion 
```
Compose doesn't use version to select an exact schema to validate the Compose file, but prefers the most recent schema when it's implemented.
Reference: [link](https://github.com/compose-spec/compose-spec/blob/main/spec.md#version-top-level-element-obsolete)

chore(docker-compose): remove top-level `version` attribute

---

src/instana/instrumentation/kafka/confluent_kafka_python.py
src/instana/instrumentation/kafka/kafka_python.py
src/instana/propagators/base_propagator.py
src/instana/propagators/kafka_propagator.py
src/instana/tracer.py
tests/clients/kafka/test_confluent_kafka.py
tests/clients/kafka/test_kafka_python.py

Fix the context propagation for Kafka instrumentations. This must be merged before the Kafka FUP PRs.
Signed-off-by: Cagri Yonca <cagri@ibm.com>
Co-authored-by: Paulo Vital <paulo.vital@ibm.com>

fix: Kafka context propagation

---

.circleci/config.yml
.github/workflows/py3140_build.yml
Dockerfile-py3140
tests/clients/test_sqlalchemy.py
tests/requirements-pre314.txt

This PR proposes to fix the CircleCI failure when running the tests on top of Python 3.14.0. 
It uses a GitHub Actions workflow to build a container image with all test dependencies and publish it in the GitHub Container Registry every Monday and Wednesday at 00:01. This was pre-tested in a personal repository [here](https://github.com/pvital/stunning-octo-couscous).
In addition, this PR modified the CircleCI configuration file to use matrix parameters and point to the new container image as the base image to test Python 3.14.0.

Fix Python 3.14.0 CI failures

---

tests/conftest.py
tests/requirements-pre314.txt
tests/requirements.txt

``` python
venv/lib/python3.9/site-packages/sanic/pages/error.py:4: in <module>
import tracerite.html
venv/lib/python3.9/site-packages/tracerite/__init__.py:1: in <module>
from .html import html_traceback
venv/lib/python3.9/site-packages/tracerite/html.py:3: in <module>
from .trace import extract_chain
venv/lib/python3.9/site-packages/tracerite/trace.py:11: in <module>
from .inspector import extract_variables
E     File "/root/repo/venv/lib/python3.9/site-packages/tracerite/inspector.py", line 119
E       except AttributeError, TypeError:
E                            ^
E   SyntaxError: invalid syntax
```
Error comes from [this](https://github.com/sanic-org/tracerite/pull/17/files#diff-5d409ed00bbdfa1af787bb228eada817ee27013f88370edde4698bc86f9ad9b0R122) change that was released in the …

Fix: CI errors with sanic

---

src/instana/util/config.py
tests/util/test_config.py
tests/util/test_config_reader.py
tests/util/test_configuration-2.yaml

Added similar functionality below
https://www.ibm.com/docs/en/instana-observability/current?topic=nodejs-collector-configuration#ignoring-endpoints

feat: added single method option to configuration.yaml

---

bin/aws-lambda/build_and_publish_lambda_layer.py

Added the new AWS region `ap-east-2` to publish script.

Add new AWS region to publish script.

---

src/instana/options.py
src/instana/util/config.py
tests/util/test_config.py

Add `is_truthy()` function to accept `True`, `true`, and `1` as boolean `True` values when reading environment variables. This makes configuration more flexible and user-friendly.
- Add new `is_truthy()` utility function in config.py
- Update environment variable checks in options.py to use the new function
- Add parametrized tests to verify functionality with various input values

feat(config): add support for multiple boolean formats in environment variables.

---

src/instana/instrumentation/aio_pika.py
tests/clients/test_aio_pika.py

According to the [official Python documentation](https://docs.python.org/3/tutorial/controlflow.html#positional-or-keyword-arguments), 
By default, arguments may be passed to a Python function either by `position` or explicitly by `keyword`.
Hence in this change, we accept `message` & `routing_key` from either `args` or `kwargs`.

fix(aio-pika): Extract  `message` & `routing_key` from either `args` or `kwargs`

---

src/instana/__init__.py
src/instana/instrumentation/logging.py
src/instana/options.py
src/instana/util/config.py
src/instana/util/config_reader.py
tests/clients/test_logging.py
tests/test_options.py
tests/test_span_disabling.py
tests/util/test_config_reader.py
tests/util/test_configuration-1.yaml
tests/util/test_configuration-2.yaml

We need to disable log collection at the tracer level to prevent duplication in the backend when both the application tracer and an OpenTelemetry collector are running on the same system.
This PR adds support for the Span Disabling feature, which allows the exclusion of specific traces or calls from tracing based on the category (technology) or type (frameworks, libraries, instrumentations) supported by the traces.
In addition, it refactors the initialization of the Instana module and the ConfigReader class.

Disabling log collection at the tracer level

---

pyproject.toml
src/instana/span/base_span.py
tests/clients/test_google-cloud-pubsub.py
tests/clients/test_google-cloud-storage.py

The package `six` was used to bridge the gap between Python 2 and Python 3 but since we have removed support for Python 2 long back, it would only make sense to completely remove its usage from our codebase.

Remove six package and its usage since Python 2 is no longer supported

---

src/instana/instrumentation/aws/s3.py
tests/clients/boto3/test_boto3_s3.py

This PR fixes the errors described in https://github.com/instana/python-sensor/issues/769.
Not only does it update the code to properly fetch the bucket name for upload_fileobj it also ensures we don't hide proper exceptions from the client

Update AWS wrapper to not hide proper exceptions

---

.github/scripts/announce_pr_on_slack.py
.github/scripts/announce_release_on_slack.py
.github/workflows/opened-pr-notification-on-slack.yml

Fix Slack GH Actions

---

.tekton/.currency/currency-scheduled-eventlistener.yaml
.tekton/.currency/currency-tasks.yaml
.tekton/github-pr-pipeline.yaml.part
.tekton/github-set-status-task.yaml
.tekton/pipeline.yaml
.tekton/python-tracer-prepuller.yaml
.tekton/scheduled-eventlistener.yaml
.tekton/task.yaml

1. Updated Python versions and container images tags.
2. Updated PR pipeline to test all necessary cases.
3. Updated scheduled pipelines. Now the currency pipeline executes after 1h30 the start of the daily pipeline.

ci: Update Tekton pipelines

---

src/instana/instrumentation/urllib3.py
tests/clients/test_urllib3.py

Add internal span filtering for internal HTTP calls.

Internal Span Filtering

---

src/instana/agent/host.py
src/instana/fsm.py
src/instana/util/process_discovery.py
tests/agent/test_host.py

This PR:
1. Format the `TheMachine` and `Discovery` classes by adding type annotations to the `fsm.py` file and using `ruff`.
2. Refactor the `Discovery` class by changing it to a `DataClass`, and move it out of the fsm.py file.
3. Add support to announce Windows processes. The implementation gracefully handles platform differences, ensuring consistent process information on both Unix and Windows environments:
- Created a new `_get_cmdline()` function to return the command line of the current monitored process independently of the running platform.
- Created the `_get_cmdline_windows()` function to return the command line on Windows machines.
- Created `_get_cmdline_unix()` that returns the command line in Unix machines. It decides how to collect the information by running either the ` …

Fix announce of processes on Windows.

---

src/instana/instrumentation/kafka/confluent_kafka_python.py
src/instana/instrumentation/kafka/kafka_python.py
tests/clients/kafka/test_confluent_kafka.py
tests/clients/kafka/test_kafka_python.py

Fixed trace correlation issues, aligned with other tracers through the tracer-test-suite.

Kafka FUP Final

---

src/instana/instrumentation/aio_pika.py
tests/clients/test_aio_pika.py

Addresses #794.
The following changes were made:
- Move the execution of the consumer callback in the `aio-pika´ consume wrapper into the `with` statement that constitutes the consumer span. This enables tracing of further calls made in the consumer callback function.
- Add a test to check if exceptions thrown in the consumer callback function are recorded by Instana. This fails against the current `main` branch and passes with the changes in this PR.

[aio-pika] Enable consumer callback tracing

---

src/instana/propagators/http_propagator.py
tests/propagators/test_http_propagator.py

Fix the bug `Immutable type, ignoring call to set attribute`
```python
[DEBUG]	2025-09-03T09:02:26.013Z	8ed186f7-0c6a-4407-815e-fb3bc2f5c277	Immutable type, ignoring call to set attribute
Stack (most recent call last):
File "/var/runtime/bootstrap.py", line 60, in <module>
main()
File "/var/runtime/bootstrap.py", line 57, in main
awslambdaricmain.main([os.environ["LAMBDA_TASK_ROOT"], os.environ["_HANDLER"]])
File "/var/runtime/awslambdaric/__main__.py", line 21, in main
bootstrap.run(app_root, handler, lambda_runtime_api_addr)
File "/var/runtime/awslambdaric/bootstrap.py", line 529, in run
handle_event_request(
File "/var/runtime/awslambdaric/bootstrap.py", line 177, in handle_event_request
response = request_handler(event, lambda_context)
File "/opt/python/instana/__init__.py", line 146, …
```

fix: `Immutable type, ignoring call to set attribute` on span_context
